In [12]:

a = torch.arange(1, 17)  # a's shape is (16,)
 
a.view(-1,2,2) # output below

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])

In [ ]:
[    1,   474,   763,   304,  1083, 27224, 17774, 29889,    13, 29875,
          763,   304,   748, 29826, 29889,    13, 29875,   763,   304, 15049,
          263, 12580, 29889,    13,  1357, 25448,  8753, 22394,   338, 12713,
         4657,   264, 29889,    13,  2918,  1919,   920,   526,   366,  2599,
         1577,   474, 29915, 29885,  2805,  7960,   304,   437,   777,   923,
          300,   801,   521,  5832,   304,  7952,   297,  8267,   869,    13,
         6293,  1818,   367,  1407,  5172,   869, 29826,   338,   697,   310,
          590, 25448,   298, 20838,   583,   869,    13, 29875,   626,  1738,
          363,   590,   298,   711,  1609,   474,   763,   304,   437,   508,
         1076,   470,   777,   377,   986,  1847,   869, 

.
.[    0,     0,   474,   763,   304,  1083, 27224, 17774, 29889,     0,
           474,   763,   304,   748, 29826, 29889,     0,   474,   763,   304,
         15049,   263, 12580, 29889,     0,   590, 25448,  8753, 22394,   338,
         12713,  4657,   264, 29889,     0,     0,  7251,  1919,   920,   526,
           366,  2599,  1577,   474, 29915, 29885,  2805,  7960,   304,   437,
           777,   923,   300,   801,   521,  5832,   304,  7952,   297,  8267,
           869,     2,     0,   366,  1818,   367,  1407,  5172,   869, 29826,
           338,   697,   310,   590, 25448,   298, 20838,   583,   869,     2,
             0,   474,   626,  1738,   363,   590,   298,   711,  1609,   474,
           763,   304,   437,   508,  1076,   470,   777,   377,   986,  1847,
           869,     2, 

In [2]:
from torch.nn.utils.rnn import pad_sequence
import torch
import numpy as np
from transformers import AutoTokenizer
from transformers import LlamaForCausalLM
pad_id = 0
item_mine = [[2, 2, 939, 1166, 10328, 2799, 10, 76, 4, 939, 437, 10, 16391, 1457, 25, 127, 200, 633, 4, 939, 129, 3529, 36930, 4, 939, 21, 1179, 11, 10, 881, 4095, 6028, 4, 2, 20760, 99, 32, 608, 452, 17487, 2], 
             [2, 2, 939, 1166, 10328, 2799, 10, 76, 4, 939, 437, 10, 16391, 1457, 25, 127, 200, 633, 4, 939, 129, 3529, 36930, 4, 939, 21, 1179, 11, 10, 881, 4095, 6028, 4, 2, 20760, 99, 32, 608, 452, 17487, 2]]
             
item = [[50267, 50268, 939, 657, 2982, 2596, 1245, 8, 14926, 5282, 18292, 4, 2, 939, 657, 7, 1930, 86, 19, 127, 284, 4, 2, 939, 437, 10, 1928, 2996, 9008, 4, 2, 939, 1656, 130, 1788, 358, 183, 4, 2], 
        [50267, 50268, 939, 657, 2982, 2596, 1245, 8, 14926, 5282, 18292, 4, 2, 939, 657, 7, 1930, 86, 19, 127, 284, 4, 2, 939, 437, 10, 1928, 2996, 9008, 4, 2, 939, 1656, 130, 1788, 358, 183, 4, 2]]

In [15]:
item_mine = pad_sequence([torch.from_numpy(np.array(x)) for x in item_mine],
                                  batch_first=True, padding_value=pad_id)

In [142]:
#tokenizer = AutoTokenizer.from_pretrained("/checkpoint/llama_7B/", padding_side="right", use_fast=False)
tokenizer = AutoTokenizer.from_pretrained(
    "./checkpoint/llama_7B",
    padding_side="right",
    use_fast=False,
)
#model = LlamaForCausalLM.from_pretrained("./checkpoint/llama_7B")

In [143]:
tokenizer.eos_token = '<\s>'
tokenizer.bos_token = '<s>'
special_tokens_dict = {"sep_token": "<\sep>", "pad_token": "<\pad>"}
tokenizer.add_special_tokens(special_tokens_dict)
tokenizer.add_tokens(['<query>', '<response>', '<latent>', '<persona>'])

4

In [144]:
print(tokenizer.bos_token_id, tokenizer.eos_token_id, tokenizer.pad_token_id, tokenizer.sep_token_id)
print(tokenizer.bos_token, tokenizer.eos_token, tokenizer.pad_token, tokenizer.sep_token)
print(tokenizer.convert_tokens_to_ids(['<query>', '<response>', '<latent>', '<persona>']))

1 2 32001 32000
<s> <\s> <\pad> <\sep>


4

In [51]:
tokenizer.sep_token='<\s>'

In [72]:
tokenizer.eos_token = '<\s>'

In [73]:
print(tokenizer.eos_token)

<\s>


In [74]:
prompt = '<\s>'
inputs = tokenizer(prompt, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[    1,   529, 29905, 29879, 29958]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}


In [24]:
generate_ids = model.generate(inputs.input_ids, max_length=30)
print(generate_ids)

tensor([[    1, 18637, 29892,   526,   366, 19861, 29973,  1815,   366,  5193,
           304,   592, 29973,    13, 29902, 29915, 29885,   451,  1854,   565,
           366, 29915,   276, 19861, 29892,   541,   306, 29915, 29885,  2675]])


[0, 0, 0, 0]


In [32]:
tokenizer.decode(inputs['input_ids'][0])

' <\\s>'

In [ ]:
print(tokenizer.decode(['hello']))

In [82]:
a = tokenizer.get_vocab()

In [85]:
a = {v : k for k, v in a.items()}

In [96]:
print(a[50])

<0x2F>


In [112]:
import torch
from transformers import GPT2Tokenizer, GPT2DoubleHeadsModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2DoubleHeadsModel.from_pretrained('gpt2')

choices = [ "Bob likes candy ; what does Bob like ?  Bag <|endoftext|>",
                   "Bob likes candy ; what does Bob like ?  Burger <|endoftext|>",
                   "Bob likes candy ; what does Bob like ?  Candy <|endoftext|>",
                  "Bob likes candy ; what does Bob like ?  Apple <|endoftext|>"]

encoded_choices = [tokenizer.encode(s) for s in choices]

eos_token_location = [tokens.index(tokenizer.eos_token_id) for tokens in encoded_choices]
input_ids = torch.tensor(encoded_choices).unsqueeze(0) 
mc_token_ids = torch.tensor([eos_token_location]) 
print(input_ids.shape)
print(mc_token_ids.shape)
outputs = model(input_ids, mc_token_ids=mc_token_ids)
lm_prediction_scores, mc_prediction_scores = outputs[:2]


Some weights of GPT2DoubleHeadsModel were not initialized from the model checkpoint at gpt2 and are newly initialized: ['multiple_choice_head.summary.bias', 'multiple_choice_head.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


torch.Size([1, 4, 13])
torch.Size([1, 4])
torch.Size([1, 4, 13, 50257])
tensor([[4.9233, 4.9585, 4.9521, 4.9414]], grad_fn=<SqueezeBackward1>)


In [113]:
print(lm_prediction_scores.shape)
print(mc_prediction_scores.shape)

torch.Size([1, 4, 13, 50257])
torch.Size([1, 4])


In [15]:
import wandb, random
total_step_num = 1000
for step in range(total_step_num):
    wandb.log({'random_curve':step/100+random.random()},step=step)
    wandb.log({'log_curve': math.log(step+1)},step=step)
wandb.finish()

Error: You must call wandb.init() before wandb.log()

In [ ]:
wandb.login()

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

In [ ]:
import random

# Launch 5 simulated experiments
total_runs = 5
for run in range(total_runs):
  # 🐝 1️⃣ Start a new run to track this script
  wandb.init(
      # Set the project where this run will be logged
      project="wandbexample1", 
      # We pass a run name (otherwise it’ll be randomly assigned, like sunshine-lollypop-10)
      name=f"experiment_{run}", 
      # Track hyperparameters and run metadata
      config={
      "learning_rate": 0.02,
      "architecture": "CNN",
      "dataset": "CIFAR-100",
      "epochs": 10,
      })
  
  # This simple block simulates a training loop logging metrics
  epochs = 10
  offset = random.random() / 5
  for epoch in range(2, epochs):
      acc = 1 - 2 ** -epoch - random.random() / epoch - offset
      loss = 2 ** -epoch + random.random() / epoch + offset
      
      # 🐝 2️⃣ Log metrics from your script to W&B
      wandb.log({"acc": acc, "loss": loss})
      
  # Mark the run as finished
  wandb.finish()

